In [5]:
import pandas as pd
import numpy as np

# Create a data frame with 50 rows and 5 columns
rows = 50
df = pd.DataFrame({'A': np.random.randn(rows),
                   'B': np.random.randn(rows),
                   'C': np.random.randn(rows),
                   'D': np.random.randn(rows),
                   'E': np.random.randn(rows)})

print(df.head(50))


           A         B         C         D         E
0  -0.637715 -0.008716  2.441722  0.466834  0.340092
1   0.941946  1.135892  0.953508 -1.013503 -0.317948
2  -1.485563  0.003405  1.241650  0.716231 -0.804084
3  -1.297048  0.386250 -1.298859 -1.079131 -0.186403
4  -0.874042  0.375405  0.470465 -1.390061  0.591363
5  -0.762395 -1.189454 -0.315518 -0.035817 -0.139094
6  -0.811501  0.205511 -1.106144  0.413437  0.932235
7   0.494827 -0.154476  0.971261 -0.761147  0.449731
8  -1.133869  0.239657  0.330738 -0.610406 -0.917744
9   0.000090  2.801344  0.265729  1.262680  0.000305
10 -0.492554 -2.239369 -0.095144  0.923799 -0.411607
11 -0.205872  0.775319  0.398879 -0.165948  0.326102
12  0.889496 -0.741061  0.055506 -0.182819 -1.586499
13 -0.694378  0.078617  2.128228  0.093340  0.456868
14 -0.433485 -1.286493 -0.199488 -1.015546  0.728872
15 -1.648392  0.128016 -0.368874  0.072786  0.400837
16 -2.166542 -1.620683  0.399683 -0.668982  2.342297
17  0.229531  0.839420 -0.673909 -0.090225 -0.

In [7]:
df.describe()

A          B          C          D          E
count  50.000000  50.000000  50.000000  50.000000  50.000000
mean   -0.058234  -0.215652   0.236339  -0.226103  -0.202779
std     1.019750   1.211430   1.059259   1.071053   0.965417
min    -2.427986  -2.917675  -1.901788  -1.978756  -2.428546
25%    -0.680212  -1.046459  -0.565260  -1.015036  -0.759880
50%     0.007474  -0.116515   0.298234  -0.268713  -0.079379
75%     0.617110   0.383538   0.855275   0.375064   0.436099
max     2.068219   2.801344   2.755159   2.344446   2.342297

In [8]:
df["A"].describe()

count    50.000000
mean     -0.058234
std       1.019750
min      -2.427986
25%      -0.680212
50%       0.007474
75%       0.617110
max       2.068219
Name: A, dtype: float64

In [9]:
df.corr()

A         B         C         D         E
A  1.000000 -0.041433 -0.033542 -0.074252 -0.100357
B -0.041433  1.000000 -0.028360 -0.001044  0.278640
C -0.033542 -0.028360  1.000000  0.062063 -0.230605
D -0.074252 -0.001044  0.062063  1.000000 -0.237403
E -0.100357  0.278640 -0.230605 -0.237403  1.000000

In [10]:
df.cov()

A         B         C         D         E
A  1.039891 -0.051185 -0.036231 -0.081098 -0.098800
B -0.051185  1.467562 -0.036392 -0.001354  0.325880
C -0.036231 -0.036392  1.122029  0.070411 -0.235823
D -0.081098 -0.001354  0.070411  1.147155 -0.245478
E -0.098800  0.325880 -0.235823 -0.245478  0.932031

In [11]:
df.kurt()

A    0.057759
B    0.228080
C    0.007822
D   -0.126088
E    0.446291
dtype: float64

In [12]:
df.mad()

C:\Users\admin\AppData\Local\Temp\ipykernel_3304\3844944795.py:1: FutureWarning: The 'mad' method is deprecated and will be removed in a future version. To compute the same result, you may do `(df - df.mean()).abs().mean()`.
  df.mad()


A    0.788810
B    0.949309
C    0.832927
D    0.842755
E    0.746001
dtype: float64

In [13]:
df.sem()

A    0.144214
B    0.171322
C    0.149802
D    0.151470
E    0.136531
dtype: float64

In [15]:
df.var()

A    1.039891
B    1.467562
C    1.122029
D    1.147155
E    0.932031
dtype: float64

In [16]:
df["A"].value_counts()

-0.637715    1
 0.436767    1
 0.662418    1
 0.698217    1
-2.427986    1
 1.473943    1
-0.053598    1
-0.162644    1
 1.400278    1
-0.051492    1
-1.299959    1
-0.231523    1
 0.234953    1
 0.941946    1
 0.306189    1
 0.783586    1
 0.164713    1
 0.746978    1
-0.540089    1
 1.690071    1
 2.068219    1
-2.274477    1
-0.397040    1
 0.268656    1
-0.966100    1
 0.014857    1
 0.316799    1
 0.221632    1
-1.485563    1
-1.297048    1
-0.874042    1
-0.762395    1
-0.811501    1
 0.494827    1
-1.133869    1
 0.000090    1
-0.492554    1
-0.205872    1
 0.889496    1
-0.694378    1
-0.433485    1
-1.648392    1
-2.166542    1
 0.229531    1
-0.022566    1
 1.858094    1
 0.303611    1
 0.657872    1
 0.332202    1
 0.963163    1
Name: A, dtype: int64

In [25]:
pd.crosstab(index=df['A'],
 columns=df['B'])

B          -2.917675  -2.239369  -2.158725  -2.097964  -2.087713  -1.620683  \
A                                                                             
-2.427986          0          0          0          0          0          0   
-2.274477          0          0          0          0          0          0   
-2.166542          0          0          0          0          0          1   
-1.648392          0          0          0          0          0          0   
-1.485563          0          0          0          0          0          0   
-1.299959          0          0          0          0          0          0   
-1.297048          0          0          0          0          0          0   
-1.133869          0          0          0          0          0          0   
-0.966100          0          0          0          0          0          0   
-0.874042          0          0          0          0          0          0   
-0.811501          0          0          0          0          0          0   
-0.762395          0          0          0          0          0          0   
-0.694378          0          0          0          0          0          0   
-0.637715          0          0          0          0          0          0   
-0.540089          0          0          0          1          0          0   
-0.492554          0          1          0          0          0          0   
-0.433485          0          0          0          0          0          0   
-0.397040          0          0          0          0          0          0   
-0.231523          0          0          0          0          0          0   
-0.205872          0          0          0          0          0          0   
-0.162644          0          0          0          0          0          0   
-0.053598          0          0          0          0          0          0   
-0.051492          0          0          0          0          0          0   
-0.022566          0          0          0          0          1          0   
 0.000090          0          0          0          0          0          0   
 0.014857          0          0          0          0          0          0   
 0.164713          0          0          1          0          0          0   
 0.221632          0          0          0          0          0          0   
 0.229531          0          0          0          0          0          0   
 0.234953          0          0          0          0          0          0   
 0.268656          0          0          0          0          0          0   
 0.303611          0          0          0          0          0          0   
 0.306189          0          0          0          0          0          0   
 0.316799          0          0          0          0          0          0   
 0.332202          0          0          0          0          0          0   
 0.436767          0          0          0          0          0          0   
 0.494827          0          0          0          0          0          0   
 0.657872          1          0          0          0          0          0   
 0.662418          0          0          0          0          0          0   
 0.698217          0          0          0          0          0          0   
 0.746978          0          0          0          0          0          0   
 0.783586          0          0          0          0          0          0   
 0.889496          0          0          0          0          0          0   
 0.941946          0          0          0          0          0          0   
 0.963163          0          0          0          0          0          0   
 1.400278          0          0          0          0          0          0   
 1.473943          0          0          0          0          0          0   
 1.690071          0          0          0          0          0          0   
 1.858094          0          0          0        

In [29]:
df.rank()

A     B     C     D     E
0   14.0  27.0  49.0  41.0  35.0
1   44.0  45.0  41.0  14.0  21.0
2    5.0  28.0  45.0  42.0  13.0
3    7.0  38.0   5.0  11.0  23.0
4   10.0  37.0  31.0   7.0  44.0
5   12.0  11.0  18.0  32.0  24.0
6   11.0  32.0   6.0  40.0  46.0
7   37.0  24.0  42.0  18.0  39.0
8    8.0  33.0  26.0  23.0  11.0
9   25.0  50.0  25.0  44.0  28.0
10  16.0   2.0  20.0  43.0  18.0
11  20.0  41.0  27.0  28.0  34.0
12  43.0  18.0  22.0  27.0   6.0
13  13.0  29.0  46.0  36.0  40.0
14  17.0  10.0  19.0  13.0  45.0
15   4.0  31.0  17.0  35.0  37.0
16   3.0   6.0  28.0  20.0  50.0
17  29.0  42.0   9.0  29.0  17.0
18  24.0   5.0  24.0  46.0  19.0
19  49.0   8.0  39.0   6.0   8.0
20  32.0  44.0  15.0  48.0  38.0
21  38.0   1.0  30.0  17.0  10.0
22  35.0  39.0   8.0   8.0  30.0
23  28.0  19.0  35.0  30.0  42.0
24  34.0  34.0  33.0   9.0  36.0
25  26.0  49.0  14.0  19.0  48.0
26   9.0  40.0  16.0  33.0   7.0
27  39.0  43.0  37.0   4.0  12.0
28  40.0  22.0  12.0  12.0  43.0
29   1.0  35.0  50.0  49.0   5.0
30  47.0  20.0  48.0  24.0  16.0
31  22.0  23.0  32.0   1.0   9.0
32  21.0  36.0   3.0  10.0  33.0
33  46.0  15.0  11.0  26.0  22.0
34  23.0  47.0  44.0  21.0  14.0
35   6.0   7.0  23.0  22.0   2.0
36  19.0   9.0  38.0  16.0  27.0
37  36.0  17.0  34.0   2.0  26.0
38  30.0  21.0   7.0  50.0  15.0
39  33.0  46.0  13.0  39.0  41.0
40  42.0  48.0  10.0  31.0  49.0
41  27.0   3.0   2.0  38.0  29.0
42  41.0  13.0  47.0  47.0   1.0
43  15.0   4.0   4.0  37.0   4.0
44  48.0  26.0   1.0  34.0  32.0
45  50.0  14.0  40.0  45.0   3.0
46   2.0  30.0  21.0  15.0  20.0
47  18.0  16.0  29.0   5.0  25.0
48  31.0  25.0  43.0  25.0  47.0
49  45.0  12.0  36.0   3.0  31.0

In [31]:
np.histogram(df['A'])

(array([ 3,  1,  4,  6,  6, 11,  9,  5,  2,  3], dtype=int64),
 array([-2.4279858 , -1.97836534, -1.52874489, -1.07912443, -0.62950398,
        -0.17988352,  0.26973693,  0.71935739,  1.16897784,  1.6185983 ,
         2.06821875]))

In [33]:
np.histogram(df['C'], bins=5)

(array([ 6, 14, 18,  7,  5], dtype=int64),
 array([-1.90178767, -0.97039826, -0.03900884,  0.89238058,  1.82377   ,
         2.75515941]))

In [34]:
np.histogram(df['A'],
 bins=[-3,-2,-1,0,1,2,3,4])


(array([ 3,  5, 16, 21,  4,  1,  0], dtype=int64),
 array([-3, -2, -1,  0,  1,  2,  3,  4]))